services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    expose:
      - 6333
      - 6334
    configs:
      - source: qdrant_config
        target: /etc/qdrant/config.yml
    volumes:
      - ./qdrant_data:/var/lib/qdrant
networks:
  default:
    name: vector-index-network
    
configs:
  qdrant_config:
    content: |
      log_level: INFO